version: '3.2'
services:
  web:
    image: nginx-update
    ports:
      - "8383:80"
    volumes:
      - ./site-content:/usr/share/nginx/html
      - ./conf:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/ 
    network_mode: "bridge"    
